### ISSUE TITLE
Duplicate key warning.

### ISSUE THREAD

**Issue by SamSteele01** [ngthorg/react-es7-snippets#3]
Every new window opened has the error message in a red/pink window:

Failed to load snippets from '/Users/samsteele 1/.atom/packages/react-es7-snippets/snippets/React (ES7).cson'

/Users/samsteele 1/.atom/packages/react-es7-snippets/snippets/React (ES7).cson: Duplicate key 'React ES7 Component'

Have you seen this yet? Do you know of a quick fix? 

I uninstalled and reinstalled the package. It did not fix the issue.

**Comment by jfluhmann82** [comment]
@SamSteele01 
I had the same issue just while ago too.  Here is how I fixed it (you need to edit two lines of the .cson file):
Edit line 49 of the .cson file you listed in your question from 'React ES7 Component' to 'React ES7 Component with Props'
and Edit line 95 of the .cson file you listed in your question from 'React ES7 Component with Constructor' to 'React ES7 Components with Constructor and Props'
That will fix your dupe issue.

**Comment by SamSteele01** [comment]
That worked. Thank you!

**Comment by karinafarina** [comment]
I'm having same issue. How do I get to that file?

**Comment by jfluhmann82** [comment]
@karinafarina, the file is located at ~/.atom/packages/react-es7-snippets/snippets/React (ES7).cson
~/ is short for your home directory (i.e. ~/ == /home/jfluhmann/ or /Users/jfluhmann/ depending on OS you're on).
